<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\$(RevitVersion)\$(Configuration)\</OutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateRuntimeConfigurationFiles>false</GenerateRuntimeConfigurationFiles>
    <Configurations>Debug;Release</Configurations>
    <AssemblyName>MetroCIM</AssemblyName>
    <RootNamespace>MetroCIM</RootNamespace>
    <Product>MetroCIM</Product>
    <Title>MetroCIM</Title>
    <DeployAddin Condition="'$(DeployAddin)' == ''">false</DeployAddin>
    <RevitAddinsDir>$(AppData)\Autodesk\Revit\Addins\$(RevitVersion)\</RevitAddinsDir>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Nice3point.Revit.Api.RevitAPI" Version="$(RevitVersion).*" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="Nice3point.Revit.Api.RevitAPIUI" Version="$(RevitVersion).*" ExcludeAssets="runtime" PrivateAssets="all" />
    <PackageReference Include="SharpGLTF.Toolkit" Version="1.*" />
  </ItemGroup>

  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <None Include="MetroCIM.addin" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <Target Name="DeployAddin" AfterTargets="Build" Condition="'$(DeployAddin)' == 'true'">
    <MakeDir Directories="$(RevitAddinsDir)MetroCIM\" />
    <ItemGroup>
      <DeployFiles Include="$(OutputPath)*.dll" />
      <DeployFiles Include="$(OutputPath)*.pdb" />
      <DeployFiles Include="$(OutputPath)*.json" />
    </ItemGroup>
    <Copy SourceFiles="@(DeployFiles)" DestinationFolder="$(RevitAddinsDir)MetroCIM\" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\MetroCIM.addin" DestinationFolder="$(RevitAddinsDir)" SkipUnchangedFiles="true" />
    <Delete Files="$(RevitAddinsDir)RevitXKT.addin" Condition="Exists('$(RevitAddinsDir)RevitXKT.addin')" />
  </Target>

</Project>
